### ISSUE TITLE
적용된 폰트가 원본 사이트와 다릅니다.

### ISSUE THREAD

**Issue by hw9402** [ThisIsComedy/BDNS-Clone#15]
> global.style.jsx에 있는 Londrina Solid 폰트에 문제가 있는 것 같습니다. 확인 후 수정 부탁드립니다.

### 기대하는 결과
<img width="438" alt="Snipaste_2023-05-27_13-38-30" src="https://github.com/ThisIsComedy/BDNS-Clone/assets/101539249/3ba2058e-e631-4e62-a004-9e59e29f7470">

### 나온 결과
<img width="416" alt="image" src="https://github.com/ThisIsComedy/BDNS-Clone/assets/101539249/1e7b170a-109a-4fae-96f7-5f85b9af5c9c">

**Comment by hotsemiwest** [comment]
문제 확인하고 develop 브랜치에서 바로 수정한 후 알려드리면 깃 풀 땡기세요
@hw9402

**Comment by hw9402** [comment]
알겠습니다

**Comment by hotsemiwest** [comment]
확인해보니 기존에 일부 폰트들을 구글폰트에서 `@import`로 임포트해왔는데 구글폰트에서 임포트하는 방식이 불안정한 것이 원인인 것 같습니다.
그래서 구글폰트에서 임포트하는 대신 모든 폰트를 .woff로 font폴더에 저장한 다음 임포트하는 방식으로 수정했습니다.

**Comment by hotsemiwest** [comment]
문제 해결되었는지 확인 후 이슈 닫아주세요
@hw9402

**Comment by hw9402** [comment]
문제 해결됐습니다. 감사합니다.
